export default function Head() {
    return (
      <>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#2C2143" />
      </>
    );
  }
  